defaults:
  - _self_
  - env: walker2d
  - override hydra/launcher: local
  - override hydra/output: local

hydra:
  job:
    chdir: True
  searchpath :
    - file://home/bechir/RewGen4Robotic/cfg

#LLM parameters 
llm:
  provider: groq # provider of the LLM (other options are openai, groq)
  model: llama3-70b-8192 #gpt-4o  # LLM model (other options are gpt-4, gpt-4-0613, gpt-3.5-turbo-16k-0613)
  temperature: 1.0
  suffix: GROQ # suffix for generated files (indicates LLM model)
  
  
# RewGen4Robotics parameters
iteration: 1 # how many iterations of Eureka to run
sample: 1 # number of Eureka samples to generate per iteration
max_iterations: 3000 # RL Policy training iterations (decrease this to make the feedback loop faster)
num_eval: 2 # number of evaluation episodes to run for the final reward
num_eval_episodes: 1000 # number of evaluation episodes to run for the final reward
capture_video: False # whether to capture policy rollout videos
timesteps: 1000000 # number of timesteps to train the policy
